apiVersion: v1
kind: Secret
metadata:
  name: itgenius-secret
type: Opaque
data:
  DB_USERNAME: aXRnZW5pdXNhZG1pbnVzZXI=  # base64 encoded `adminuser`
  DB_PASSWORD: VVdLbms3eTY=  # base64 encoded `securepassword` command to encode is : "echo -n 'your_value' | base64"  Example command to decode is : "echo "c2VjdXJlcGFzc3dvcmQ=" | base64 --decode"
